### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by jameswu49** [jameswu49/consultation-worksheet#2]
- [x] create income table 
- [x] write conditional statements for mortgage and loans 
- [x] create success modal and error
- [ ] change index and thumbnail 
- [ ] host the site
